lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600 # in seconds, default is 3600
    user_identity_field: email # key under which the user identity will be stored in the token payload
    allow_no_expiration: false # set to true to allow tokens without exp claim
    # token extraction settings
    token_extractors:
        # look for a token as Authorization Header
        authorization_header:
            enabled: true
            prefix:  Bearer
            name:    Authorization
        # check token in a cookie
        cookie:
            enabled: true
            name:    BEARER
        # check token in query string parameter
        query_parameter:
            enabled: true
            name:    bearer
        # check token in a cookie
        split_cookie:
            enabled: true
            cookies:
                - jwt_hp
                - jwt_s
